name: Build base nginx
on:
  push:
    branches: 
      - main
    paths: 'images/nginx/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/nofirg/example-service/nginx:latest
          context: ./images/nginx
          push: true
