name: CI
on:
  push:
    branches: 
      - main
    paths: 'images/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build and push nginx
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./images/nginx
          file: ./images/nginx
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginx
